export const types = {
    CHANGE_TITLE: "[TITLE]/CHANGE_TITLE",
    CHANGE_DATA: "CHANGE_DATA",
    ADD_USER: "ADD_USER",
    CLEAR_DATA: "CLEAR_DATA",
    CLEAR_TITLE: "CLEAR_TITLE",

    HANDLE_USERS: "HANDLE_USERS"
}